# Generated by Django 5.0.14 on 2025-05-11 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('subscriptions', '0002_alter_subscriptionmodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionmodel',
            name='groups',
            field=models.ManyToManyField(to='auth.group'),
        ),
    ]
