# Generated by Django 5.0.14 on 2025-05-11 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('subscriptions', '0003_subscriptionmodel_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionmodel',
            name='permissions',
            field=models.ManyToManyField(to='auth.permission'),
        ),
    ]
