# Generated by Django 5.0.14 on 2025-05-11 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_alter_subscriptionmodel_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionmodel',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
